server:
  port: &&port&&

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://&&dbhost&&:&&dbport&&/&&dbname&&
    username: &&dbusername&&
    password: &&dbpassword&&
  jpa:
    hibernate:
      ddl-auto: update
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
