version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: "Dockerfile"
    environment:
      PORT: "8080"
      SPRING_PROFILES_ACTIVE: "prod"
    ports:
      - "8080:8080"
    volumes:
      - "./maven-repo:/root/.m2"
